Handle more than one tar file

diff --git a/unpack-download b/unpack-download
--- a/unpack-download
+++ b/unpack-download
@@ -1,19 +1,22 @@
 #!/bin/sh
 
 if [ $# -eq 0 ]; then
-   file=$HOME/Downloads/download.gz
-else
-   file=`ls $1`
-fi
-
-if [ ! -f "$file" ]; then
-    echo "$0: Cannot find input file $1 ($file)" 1>&2
+    echo "Usage: $0 SPS-pDAQ-run-XXXXXX-*.tar.gz [SPS-pDAQ-run-YYYYYY-*.tar.gz ...]"
     exit 1
 fi
 
-base=`basename $file .tar.gz`
+while [ $# -gt 0 ]; do
+    for file in $1; do
+        if [ ! -f "$file" ]; then
+            echo "$0: Cannot find input file $1 ($file)" 1>&2
+        else
+            base=`basename $file .tar.gz`
 
-tar xvzf $file &&
-rm $file $base.meta.xml &&
-tar xvf $base.dat.tar &&
-rm $base.dat.tar
+            tar xvzf $file &&
+            rm $file $base.meta.xml &&
+            tar xvf $base.dat.tar &&
+            rm $base.dat.tar
+        fi
+    done
+    shift
+done
